version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_wiki
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data_wiki:/data/db
    restart: unless-stopped

volumes:
  mongodb_data_wiki:
